pipeline {
    agent any

    environment {
        IMAGE_NAME = "hachem27/ai-content-generator-manager"
        DOCKER_TAG = "1.0.0"
        NAMESPACE = "nip"
    }

    parameters {
        string(name: 'BRANCH_NAME', defaultValue: 'main', description: 'Branche à builder')
         choice(name: 'ACTION', choices: ['build', 'deploy'], description: 'Choisir build ou deploy')
    }

    stages {

        stage('Checkout') {
            steps {
                echo "➡️ Checkout branche : ${params.BRANCH_NAME}"
                git branch: "${params.BRANCH_NAME}",
                    url: "https://github.com/MedHachem/backend-micro-services.git"
            }
        }

        stage('Navigate to MS') {
            steps {
                dir('ai-content-generator-manager') {
                    echo "➡️ On travaille dans ai-content-generator-manager"
                }
            }
        }

        stage('Build Maven') {
        when { expression { params.ACTION == 'build' } }
            steps {
                dir('ai-content-generator-manager') {
                    echo "➡️ Maven clean package"
                    sh "mvn clean package -DskipTests"
                }
            }
        }

        stage('Build Docker Image') {
        when { expression { params.ACTION == 'build' } }
            steps {
                dir('ai-content-generator-manager') {
                    echo "➡️ Build Docker image avec tag ${DOCKER_TAG}"
                    sh "docker build -t ${IMAGE_NAME}:${DOCKER_TAG} ."
                }
            }
        }

        stage('Docker Login') {
        when { expression { params.ACTION == 'build' } }
            steps {
                echo "➡️ Login Docker Hub"
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
                }
            }
        }

        stage('Push Docker Image') {
        when { expression { params.ACTION == 'build' } }
            steps {
                dir('ai-content-generator-manager') {
                    echo "➡️ Push Docker image vers Docker Hub"
                    sh "docker push ${IMAGE_NAME}:${DOCKER_TAG}"
                }
            }
        }

        stage('Cleanup') {
        
        when { expression { params.ACTION == 'build' } }
            steps {
                echo "➡️ Nettoyage des images locales"
                sh "docker rmi ${IMAGE_NAME}:${DOCKER_TAG} || true"
            }
        }
        
            stage('Deploy to Kubernetes') {
                                            when { expression { params.ACTION == 'deploy' } }
                                            steps {
                                                dir('ai-content-generator-manager/k8s') {
                                                    echo "➡️ Déploiement dans Kubernetes"
                                                     sh "kubectl create namespace ${NAMESPACE} || true"
                                                     sh "kubectl apply -f config-map.yaml -n ${NAMESPACE}"
                                                     sh "kubectl apply -f secret.yaml -n ${NAMESPACE}"
                                                    sh "kubectl apply -f ai-content-generator-manager-deployment.yaml -n ${NAMESPACE}"
                                                    sh "kubectl apply -f ai-content-generator-manager.yaml -n ${NAMESPACE}"
                                                    sh "kubectl rollout restart deployment ai-content-generator-manager -n ${NAMESPACE}"
                                                }
                                            }
                                        }
    }

    post {
        success {
            echo "✅ Pipeline réussi ! Docker image pushée : ${IMAGE_NAME}:${DOCKER_TAG}"
        }
        failure {
            echo "❌ Pipeline échoué ! Vérifie les logs."
        }
        always {
            echo "🔄 Fin du pipeline."
        }
    }
}
